### ISSUE TITLE
Demo loads a navbar with no widgets

### ISSUE THREAD

**Issue by psantann** [nickholub/angular-dashboard-app#1]
Hi Nick,

This is a pretty awesome app! Sorry this will be probably a newbie question as I'm pretty new to angular and node.js.

I'm probably just confused here but I imagined that running this app would give similar results than the demo link you put up (http://nickholub.github.io/angular-dashboard-app). Instead it only loads a navbar with links that do not work, for me:

![screen shot 2014-03-14 at 6 20 48 pm](https://f.cloud.github.com/assets/284448/2427334/3fdd5224-abe0-11e3-99d8-5c5efffaee52.png)

I tried having a server running in the bg by running dev_start.sh and then "grunt server". Also I tried just "grunt" which gave a few warnings and then "grunt --force".

Thanks,

Paulo

**Comment by nickholub** [comment]
Make sure to run "npm install" and "bower install".
After you run "grunt server" application will be available at http://127.0.0.1:9000/#/clientdata

**Comment by psantann** [comment]
Nope, that does not work either. I note that the "Client Data" link on top is actually http://127.0.0.1:9000/#clientdata but neither one works. I get no errors from either npm or bower install, "grunt server" gives the following output and the loads a new tab on chrome:

```
$ grunt server
Running "server" task

Running "clean:server" (clean) task

Running "concurrent:server" (concurrent) task

Running "copy:styles" (copy) task


Done, without errors.

Running "concat:less" (concat) task
File ".tmp/styles/main.less" created.

Done, without errors.

Running "coffee:dist" (coffee) task

Done, without errors.

Running "less:development" (less) task
File .tmp/styles/main.css created.

Running "autoprefixer:dist" (autoprefixer) task
File ".tmp/styles/main.css" created.

Running "connect:livereload" (connect) task
Started connect web server on 127.0.0.1:9000.

Running "watch" task
Waiting...
```

**Comment by wshelor** [comment]
I'm experiencing the exact same issue, both on my local machine and on my AWS ec2 linux server.  This is such a cool looking demo, but I'm just having zero luck getting it working.

**Comment by nickholub** [comment]
Thanks for patience. This is work in progress. I have updated the demo. Available at http://nickholub.github.io/angular-dashboard-app/#/
Here is how to run application with minimum dependencies (no grunt, bower required):
1) pull the latest
2) $ npm install express
3) $ node app.js
Application will be available at http://localhost:3000. Node.js will serve static files from "dist" directory (bundled JS/CSS).
Readme updated as well
https://github.com/nickholub/angular-dashboard-app#running-application-minimum-dependencies
Please let me know if this helps.

**Comment by psantann** [comment]
Awesome! It looks even better now. Thanks!
