### ISSUE TITLE
Creating a Meteorite Package for this dashboard

### ISSUE THREAD

**Issue by standino** [nickholub/angular-dashboard-app#2]
I am new to both angular and meteor. But my project do need such dashboard. Is it possible to create a Meteorite Package for this dashboard? Then, we can use it in a meteor project.

**Comment by nickholub** [comment]
Right now it is possible to connect to Meteor server using Meteor DDP protocol.
There are JavaScripts Meteor DDP clients available, e.g. https://github.com/eddflrs/meteor-ddp.
Example - MeteorTimeSeriesDataModel.
https://github.com/nickholub/angular-dashboard-app/blob/master/app/scripts/services/datamodel.js

**Comment by standino** [comment]
Thanks.
