### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ReinierGielen** [nickholub/angular-dashboard-app#4]
First of all this is a great directive. Look great and works nice in the demo.

Now I have included the directive in my project and I am trying to make it work.

I get the dashboard with minimal effort with the default widgets. I can also change the default widgets. But I get only 1 column of widgets and I am not getting the widgets-options icon. And my widgets are not resizable.

Also I am wondering where I can influence the widgets layout.

These are probably setting I did wrong, but due to the lack of documentation I am a bit stuck. In the docs folder is only an image of the example.

Can you please help me.

**Comment by andyperlitch** [comment]
It sounds like you may have forgotten to include the angular-ui-dashboard.css file. See if that changes things. Also keep in mind that the icons rely on bootstrap 3. 

Beyond that you might want to post your code so we can help. 

As for the docs, we are working to improve them, and in fact yesterday I added quite a bit to the readme. It's a new project so there are still a lot of things on the todo list. We do accept pull requests!

**Comment by andyperlitch** [comment]
Apologies , I added to the [angular-ui-dashboard](https://github.com/nickholub/angular-ui-dashboard) readme.

**Comment by nickholub** [comment]
Simple demo was added here (minimum configuration) https://github.com/nickholub/angular-ui-dashboard/tree/master/demo
Deployed online http://nickholub.github.io/angular-ui-dashboard/#/
JavaScript code https://github.com/nickholub/angular-ui-dashboard/blob/master/demo/demo.js

**Comment by nickholub** [comment]
Hope this information helps. Closing the issue. Please open another one in https://github.com/nickholub/angular-ui-dashboard if there is anything else related to the dashboard directive.
